// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: promotion.proto

package promotionservice

import (
	"context"

	"github.com/aether-defense-system/service/promotion/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DecrStockRequest  = rpc.DecrStockRequest
	DecrStockResponse = rpc.DecrStockResponse

	PromotionService interface {
		// Decrement Inventory Interface
		DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error)
	}

	defaultPromotionService struct {
		cli zrpc.Client
	}
)

func NewPromotionService(cli zrpc.Client) PromotionService {
	return &defaultPromotionService{
		cli: cli,
	}
}

// Decrement Inventory Interface
func (m *defaultPromotionService) DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error) {
	client := rpc.NewPromotionServiceClient(m.cli.Conn())
	return client.DecrStock(ctx, in, opts...)
}
