# yaml-language-server: $schema=none
# golangci-lint configuration for Aether-Defense-System
# See https://golangci-lint.run/usage/configuration/ for more details
# Schema validation disabled - this config is valid for golangci-lint v1.55.2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - node_modules
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    check-err-return: true

  goconst:
    min-len: 3
    min-occurrences: 2

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/aether-defense-system

  govet:
    check-shadowing: true
    enable-all: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Errors unhandled (we use errcheck)
      - G107  # Potential HTTP request made with variable url
      - G402  # TLS InsecureSkipVerify set true

  misspell:
    locale: US

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false

  unparam:
    check-exported: false

  # godox disabled - TODO comments are acceptable during development
  # godox:
  #   keywords:
  #     - NOTE
  #     - OPTIMIZE
  #     - HACK

  godot:
    scope: declarations
    exclude:
      - "^TODO:"
      - "^FIXME:"
      - "^BUG:"

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  lll:
    line-length: 120

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: error-return
        severity: error
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: var-declaration
        severity: warning
        disabled: false
      - name: range-val-in-closure
        severity: error
        disabled: false
      - name: range-val-address
        severity: error
        disabled: false
      - name: waitgroup-by-value
        severity: error
        disabled: false
      - name: atomic
        severity: warning
        disabled: false
      - name: empty-block
        severity: warning
        disabled: false
      - name: superfluous-else
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: false
      - name: unhandled-error
        severity: error
        disabled: false

linters:
  enable:
    # Code formatting
    - gofmt
    - goimports

    # Static analysis
    - govet
    - staticcheck
    - unused
    - gosimple

    # Error handling
    - errcheck
    - errorlint

    # Security
    - gosec

    # Performance
    - prealloc
    - unconvert
    - unparam

    # Code quality
    - goconst
    - gocritic
    - ineffassign
    - misspell
    - revive
    - lll

    # Documentation
    - godot
    # - godox  # Disabled: TODO comments are acceptable during development

    # Style
    - gofumpt
    - whitespace

issues:
  exclude-rules:
    # go-zero config uses json tag options like ",optional" which SA5008 doesn't recognize.
    - path: common/database/client\.go
      text: "SA5008"
      linters:
        - staticcheck

    # Exclude generated files
    - path: _gen\.go
      linters:
        - lll
        - errcheck
        - gosec

    # Exclude protobuf generated files
    - path: \.pb\.go$
      linters:
        - lll
        - errcheck
        - revive
        - godot

    # Allow fmt.Printf in test files (but not in production code)
    - path: _test\.go
      text: "fmt\\.Print"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
