// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trade.proto

package server

import (
	"context"

	"github.com/aether-defense-system/service/trade/rpc"
	"github.com/aether-defense-system/service/trade/rpc/internal/logic"
	"github.com/aether-defense-system/service/trade/rpc/internal/svc"
)

type TradeServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedTradeServiceServer
}

func NewTradeServiceServer(svcCtx *svc.ServiceContext) *TradeServiceServer {
	return &TradeServiceServer{
		svcCtx: svcCtx,
	}
}

// PlaceOrder places an order.
func (s *TradeServiceServer) PlaceOrder(ctx context.Context, in *rpc.PlaceOrderRequest) (*rpc.PlaceOrderResponse, error) {
	l := logic.NewPlaceOrderLogic(ctx, s.svcCtx)
	return l.PlaceOrder(in)
}

// CancelOrder cancels an order.
func (s *TradeServiceServer) CancelOrder(ctx context.Context, in *rpc.CancelOrderRequest) (*rpc.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}
