// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: promotion.proto

package server

import (
	"context"

	"github.com/aether-defense-system/service/promotion/rpc"
	"github.com/aether-defense-system/service/promotion/rpc/internal/logic"
	"github.com/aether-defense-system/service/promotion/rpc/svc"
)

type PromotionServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedPromotionServiceServer
}

func NewPromotionServiceServer(svcCtx *svc.ServiceContext) *PromotionServiceServer {
	return &PromotionServiceServer{
		svcCtx: svcCtx,
	}
}

// DecrStock decrements inventory.
func (s *PromotionServiceServer) DecrStock(ctx context.Context, in *rpc.DecrStockRequest) (*rpc.DecrStockResponse, error) {
	l := logic.NewDecrStockLogic(ctx, s.svcCtx)
	return l.DecrStock(in)
}
