// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trade.proto

// Package tradeservice provides the client interface for the trade service.
package tradeservice

import (
	"context"

	"github.com/aether-defense-system/service/trade/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderRequest  = rpc.CancelOrderRequest
	CancelOrderResponse = rpc.CancelOrderResponse
	PlaceOrderRequest   = rpc.PlaceOrderRequest
	PlaceOrderResponse  = rpc.PlaceOrderResponse

	TradeService interface {
		// Place Order Interface
		PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
		// Cancel Order Interface
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	}

	defaultTradeService struct {
		cli zrpc.Client
	}
)

func NewTradeService(cli zrpc.Client) TradeService {
	return &defaultTradeService{
		cli: cli,
	}
}

// Place Order Interface
func (m *defaultTradeService) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	client := rpc.NewTradeServiceClient(m.cli.Conn())
	return client.PlaceOrder(ctx, in, opts...)
}

// Cancel Order Interface
func (m *defaultTradeService) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	client := rpc.NewTradeServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}
