// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/promotion/rpc/promotion.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Parameters
type DecrStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"` // Course ID
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`           // Deduction Quantity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockRequest) Reset() {
	*x = DecrStockRequest{}
	mi := &file_service_promotion_rpc_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockRequest) ProtoMessage() {}

func (x *DecrStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_promotion_rpc_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockRequest.ProtoReflect.Descriptor instead.
func (*DecrStockRequest) Descriptor() ([]byte, []int) {
	return file_service_promotion_rpc_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *DecrStockRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *DecrStockRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// Response Parameters
type DecrStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Success Status
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Return Message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockResponse) Reset() {
	*x = DecrStockResponse{}
	mi := &file_service_promotion_rpc_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockResponse) ProtoMessage() {}

func (x *DecrStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_promotion_rpc_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockResponse.ProtoReflect.Descriptor instead.
func (*DecrStockResponse) Descriptor() ([]byte, []int) {
	return file_service_promotion_rpc_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *DecrStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecrStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_promotion_rpc_promotion_proto protoreflect.FileDescriptor

const file_service_promotion_rpc_promotion_proto_rawDesc = "" +
	"\n" +
	"%service/promotion/rpc/promotion.proto\x12\tpromotion\"@\n" +
	"\x10DecrStockRequest\x12\x1a\n" +
	"\bcourseId\x18\x01 \x01(\x03R\bcourseId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"G\n" +
	"\x11DecrStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Z\n" +
	"\x10PromotionService\x12F\n" +
	"\tDecrStock\x12\x1b.promotion.DecrStockRequest\x1a\x1c.promotion.DecrStockResponseB8Z6github.com/aether-defense-system/service/promotion/rpcb\x06proto3"

var (
	file_service_promotion_rpc_promotion_proto_rawDescOnce sync.Once
	file_service_promotion_rpc_promotion_proto_rawDescData []byte
)

func file_service_promotion_rpc_promotion_proto_rawDescGZIP() []byte {
	file_service_promotion_rpc_promotion_proto_rawDescOnce.Do(func() {
		file_service_promotion_rpc_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_promotion_rpc_promotion_proto_rawDesc), len(file_service_promotion_rpc_promotion_proto_rawDesc)))
	})
	return file_service_promotion_rpc_promotion_proto_rawDescData
}

var file_service_promotion_rpc_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_promotion_rpc_promotion_proto_goTypes = []any{
	(*DecrStockRequest)(nil),  // 0: promotion.DecrStockRequest
	(*DecrStockResponse)(nil), // 1: promotion.DecrStockResponse
}
var file_service_promotion_rpc_promotion_proto_depIdxs = []int32{
	0, // 0: promotion.PromotionService.DecrStock:input_type -> promotion.DecrStockRequest
	1, // 1: promotion.PromotionService.DecrStock:output_type -> promotion.DecrStockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_promotion_rpc_promotion_proto_init() }
func file_service_promotion_rpc_promotion_proto_init() {
	if File_service_promotion_rpc_promotion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_promotion_rpc_promotion_proto_rawDesc), len(file_service_promotion_rpc_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_promotion_rpc_promotion_proto_goTypes,
		DependencyIndexes: file_service_promotion_rpc_promotion_proto_depIdxs,
		MessageInfos:      file_service_promotion_rpc_promotion_proto_msgTypes,
	}.Build()
	File_service_promotion_rpc_promotion_proto = out.File
	file_service_promotion_rpc_promotion_proto_goTypes = nil
	file_service_promotion_rpc_promotion_proto_depIdxs = nil
}
