// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/trade/rpc/trade.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Parameters
type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`              // User ID, parsed from JWT Token
	CourseIds     []int64                `protobuf:"varint,2,rep,packed,name=courseIds,proto3" json:"courseIds,omitempty"` // Purchased course ID list
	CouponIds     []int64                `protobuf:"varint,3,rep,packed,name=couponIds,proto3" json:"couponIds,omitempty"` // Selected coupon ID list
	OrderId       int64                  `protobuf:"varint,4,opt,name=orderId,proto3" json:"orderId,omitempty"`            // Snowflake algorithm ID
	RealAmount    int32                  `protobuf:"varint,5,opt,name=realAmount,proto3" json:"realAmount,omitempty"`      // Order actual payment amount (cents)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_service_trade_rpc_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_trade_rpc_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_service_trade_rpc_trade_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceOrderRequest) GetCourseIds() []int64 {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

func (x *PlaceOrderRequest) GetCouponIds() []int64 {
	if x != nil {
		return x.CouponIds
	}
	return nil
}

func (x *PlaceOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderRequest) GetRealAmount() int32 {
	if x != nil {
		return x.RealAmount
	}
	return 0
}

// Response Parameters
type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`     // Order ID
	PayAmount     int32                  `protobuf:"varint,2,opt,name=payAmount,proto3" json:"payAmount,omitempty"` // Actual payment amount (in cents)
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`       // Order status (1: Pending Payment)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_service_trade_rpc_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_trade_rpc_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_service_trade_rpc_trade_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderResponse) GetPayAmount() int32 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *PlaceOrderResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Cancel Order Request Parameters
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`   // User ID, parsed from JWT Token
	OrderId       int64                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"` // Order ID to cancel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_service_trade_rpc_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_trade_rpc_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_service_trade_rpc_trade_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// Cancel Order Response Parameters
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"` // Order ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`   // Updated order status (2: Closed)
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // Whether cancellation was successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_service_trade_rpc_trade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_trade_rpc_trade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_service_trade_rpc_trade_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_service_trade_rpc_trade_proto protoreflect.FileDescriptor

const file_service_trade_rpc_trade_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/trade/rpc/trade.proto\x12\x05trade\"\xa1\x01\n" +
	"\x11PlaceOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcourseIds\x18\x02 \x03(\x03R\tcourseIds\x12\x1c\n" +
	"\tcouponIds\x18\x03 \x03(\x03R\tcouponIds\x12\x18\n" +
	"\aorderId\x18\x04 \x01(\x03R\aorderId\x12\x1e\n" +
	"\n" +
	"realAmount\x18\x05 \x01(\x05R\n" +
	"realAmount\"d\n" +
	"\x12PlaceOrderResponse\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x1c\n" +
	"\tpayAmount\x18\x02 \x01(\x05R\tpayAmount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"F\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x03R\aorderId\"a\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\x97\x01\n" +
	"\fTradeService\x12A\n" +
	"\n" +
	"PlaceOrder\x12\x18.trade.PlaceOrderRequest\x1a\x19.trade.PlaceOrderResponse\x12D\n" +
	"\vCancelOrder\x12\x19.trade.CancelOrderRequest\x1a\x1a.trade.CancelOrderResponseB4Z2github.com/aether-defense-system/service/trade/rpcb\x06proto3"

var (
	file_service_trade_rpc_trade_proto_rawDescOnce sync.Once
	file_service_trade_rpc_trade_proto_rawDescData []byte
)

func file_service_trade_rpc_trade_proto_rawDescGZIP() []byte {
	file_service_trade_rpc_trade_proto_rawDescOnce.Do(func() {
		file_service_trade_rpc_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_trade_rpc_trade_proto_rawDesc), len(file_service_trade_rpc_trade_proto_rawDesc)))
	})
	return file_service_trade_rpc_trade_proto_rawDescData
}

var file_service_trade_rpc_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_trade_rpc_trade_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),   // 0: trade.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),  // 1: trade.PlaceOrderResponse
	(*CancelOrderRequest)(nil),  // 2: trade.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 3: trade.CancelOrderResponse
}
var file_service_trade_rpc_trade_proto_depIdxs = []int32{
	0, // 0: trade.TradeService.PlaceOrder:input_type -> trade.PlaceOrderRequest
	2, // 1: trade.TradeService.CancelOrder:input_type -> trade.CancelOrderRequest
	1, // 2: trade.TradeService.PlaceOrder:output_type -> trade.PlaceOrderResponse
	3, // 3: trade.TradeService.CancelOrder:output_type -> trade.CancelOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_trade_rpc_trade_proto_init() }
func file_service_trade_rpc_trade_proto_init() {
	if File_service_trade_rpc_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_trade_rpc_trade_proto_rawDesc), len(file_service_trade_rpc_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_trade_rpc_trade_proto_goTypes,
		DependencyIndexes: file_service_trade_rpc_trade_proto_depIdxs,
		MessageInfos:      file_service_trade_rpc_trade_proto_msgTypes,
	}.Build()
	File_service_trade_rpc_trade_proto = out.File
	file_service_trade_rpc_trade_proto_goTypes = nil
	file_service_trade_rpc_trade_proto_depIdxs = nil
}
